package javaapplication14;
import javax.swing.*;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import javax.swing.ImageIcon;
public class Interface extends javax.swing.JFrame {

    /** Creates new form Interface */
    public Interface() {
        initComponents();
        jLayeredPane1.removeAll();
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        jTextField3.setOpaque(false);
        jTextField8.setOpaque(false);
        jTextField9.setOpaque(false);
        jTextField10.setOpaque(false);
        jTextField11.setOpaque(false);
        jTextField12.setOpaque(false);
        jTextField13.setOpaque(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pminterface = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jButton19 = new javax.swing.JButton();
        devinterface = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        admininterface = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        testerinterface = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout jFrame2Layout = new org.jdesktop.layout.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 561, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 211, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jLayeredPane1.setForeground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        pminterface.setBackground(new java.awt.Color(51, 51, 51));

        jLabel14.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PM InterFace");

        jLabel15.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("1 - Check Peformance of Tester and developer");

        jLabel16.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("2- Monitor Open and Closed Bugs");

        jButton13.setFont(new java.awt.Font("Serif", 2, 20)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 51, 255));
        jButton13.setText("Show all Bugs");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Serif", 2, 20)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 51, 255));
        jButton14.setText("Check Status of the Developer");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jTextField15.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("Enter Developer Name");
        jTextField15.setBorder(null);
        jTextField15.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField15.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField15.setOpaque(false);

        jTextField17.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setText("Enter Tester Name");
        jTextField17.setBorder(null);
        jTextField17.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField17.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField17.setOpaque(false);

        jButton17.setFont(new java.awt.Font("Serif", 2, 20)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 51, 255));
        jButton17.setText("Check Status of the Tester");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jButton19.setText("Show All users");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pminterfaceLayout = new org.jdesktop.layout.GroupLayout(pminterface);
        pminterface.setLayout(pminterfaceLayout);
        pminterfaceLayout.setHorizontalGroup(
            pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pminterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pminterfaceLayout.createSequentialGroup()
                        .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 460, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 460, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pminterfaceLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pminterfaceLayout.createSequentialGroup()
                                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(355, 355, 355))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pminterfaceLayout.createSequentialGroup()
                                .add(jButton13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 409, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(323, 323, 323))))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pminterfaceLayout.createSequentialGroup()
                .add(0, 164, Short.MAX_VALUE)
                .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jSeparator17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSeparator16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(63, 63, 63)
                .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton19)
                    .add(jButton14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 409, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 409, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(172, 172, 172))
        );
        pminterfaceLayout.setVerticalGroup(
            pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pminterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel14)
                .add(18, 18, 18)
                .add(jLabel15)
                .add(23, 23, 23)
                .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButton14)
                    .add(jTextField15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(40, 40, 40)
                .add(pminterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton17)
                    .add(pminterfaceLayout.createSequentialGroup()
                        .add(jTextField17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(59, 59, 59)
                .add(jButton19)
                .add(31, 31, 31)
                .add(jLabel16)
                .add(34, 34, 34)
                .add(jButton13)
                .add(0, 258, Short.MAX_VALUE))
        );

        jLayeredPane1.add(pminterface, "card4");

        devinterface.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Developer Interface");

        jLabel11.setBackground(new java.awt.Color(255, 102, 255));
        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("1 - Change Status of Bug");

        jButton11.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jButton11.setText("Change Status");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI Light", 2, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("2 - View Assigned Bugs");

        jButton12.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jButton12.setText("View Assigned Bugs for me");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "Closed" }));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Status ----->>");

        jTextField14.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("Enter BugName");
        jTextField14.setBorder(null);
        jTextField14.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField14.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jTextField14.setOpaque(false);

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bug Name -->>");

        org.jdesktop.layout.GroupLayout devinterfaceLayout = new org.jdesktop.layout.GroupLayout(devinterface);
        devinterface.setLayout(devinterfaceLayout);
        devinterfaceLayout.setHorizontalGroup(
            devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, devinterfaceLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, devinterfaceLayout.createSequentialGroup()
                        .add(jButton12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 658, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(153, 153, 153))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, devinterfaceLayout.createSequentialGroup()
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 346, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(315, 315, 315))))
            .add(devinterfaceLayout.createSequentialGroup()
                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(devinterfaceLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(devinterfaceLayout.createSequentialGroup()
                        .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, devinterfaceLayout.createSequentialGroup()
                                .add(160, 160, 160)
                                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel17)
                                    .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(devinterfaceLayout.createSequentialGroup()
                                        .add(jTextField14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, devinterfaceLayout.createSequentialGroup()
                                        .add(0, 0, Short.MAX_VALUE)
                                        .add(jComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, devinterfaceLayout.createSequentialGroup()
                                .add(285, 285, 285)
                                .add(jSeparator13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(159, 159, 159)
                        .add(jButton11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 349, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        devinterfaceLayout.setVerticalGroup(
            devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(devinterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .add(18, 18, 18)
                .add(jLabel11)
                .add(27, 27, 27)
                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17))
                .add(1, 1, 1)
                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(devinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(56, 56, 56)
                .add(jLabel12)
                .add(35, 35, 35)
                .add(jButton12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        jLayeredPane1.add(devinterface, "card5");

        admininterface.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Admin - InterFace");

        jButton6.setFont(new java.awt.Font("Serif", 2, 16)); // NOI18N
        jButton6.setText("Add User");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Serif", 2, 16)); // NOI18N
        jButton7.setText("Update User Role");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Serif", 2, 16)); // NOI18N
        jButton8.setText("Delete User");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(153, 0, 153));
        jTextField4.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Enter User name");
        jTextField4.setBorder(null);
        jTextField4.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField4.setOpaque(false);
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(153, 0, 153));
        jTextField5.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Enter User name");
        jTextField5.setBorder(null);
        jTextField5.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField5.setOpaque(false);
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1 - Adding User");

        jTextField6.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Enter New Username");
        jTextField6.setBorder(null);
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField6.setMinimumSize(new java.awt.Dimension(208, 6));
        jTextField6.setOpaque(false);
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Enter password");
        jTextField7.setBorder(null);
        jTextField7.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField7.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField7.setOpaque(false);
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tester", "Developer", "PM", "Admin" }));

        jButton9.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jButton9.setText("Show All Bugs");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2 - Update Role   -------------------------------------------------------");

        jComboBox2.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tester", "Developer", "PM", "Admin" }));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("3 - Delete User    -------------------------------------------------------");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("4 - Show All Bugs ---->>");

        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 255, 0));
        jLabel28.setText("New role");

        org.jdesktop.layout.GroupLayout admininterfaceLayout = new org.jdesktop.layout.GroupLayout(admininterface);
        admininterface.setLayout(admininterfaceLayout);
        admininterfaceLayout.setHorizontalGroup(
            admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admininterfaceLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admininterfaceLayout.createSequentialGroup()
                        .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 413, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(276, 276, 276))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admininterfaceLayout.createSequentialGroup()
                        .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 470, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(303, 303, 303))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admininterfaceLayout.createSequentialGroup()
                        .add(jButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 396, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(283, 283, 283))))
            .add(admininterfaceLayout.createSequentialGroup()
                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(admininterfaceLayout.createSequentialGroup()
                            .add(115, 115, 115)
                            .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jSeparator11)
                                .add(jTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                            .add(128, 128, 128)
                            .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel28)
                                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(admininterfaceLayout.createSequentialGroup()
                            .add(111, 111, 111)
                            .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jSeparator12)
                                .add(jTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                            .add(101, 101, 101)
                            .add(jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 383, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, admininterfaceLayout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(admininterfaceLayout.createSequentialGroup()
                                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 783, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 797, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 123, Short.MAX_VALUE))
                            .add(admininterfaceLayout.createSequentialGroup()
                                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator9)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                                .add(18, 18, 18)
                                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTextField7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .add(jSeparator10))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))))
                .add(92, 92, 92))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admininterfaceLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jLabel4)
                .add(372, 372, 372))
        );
        admininterfaceLayout.setVerticalGroup(
            admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(admininterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .add(12, 12, 12)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(admininterfaceLayout.createSequentialGroup()
                        .add(jSeparator9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admininterfaceLayout.createSequentialGroup()
                        .add(jSeparator10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jButton6)
                .add(27, 27, 27)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel28)
                .add(5, 5, 5)
                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(jLabel9)
                .add(30, 30, 30)
                .add(admininterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36)
                .add(jLabel10)
                .add(17, 17, 17)
                .add(jButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 90, Short.MAX_VALUE))
        );

        jLayeredPane1.add(admininterface, "card3");

        testerinterface.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tester InterFace");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("1 - Define A Bug");

        jTextField3.setBackground(new java.awt.Color(224, 224, 224));
        jTextField3.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setMargin(new java.awt.Insets(2, 30, 2, 2));

        jComboBox3.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBox4.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incorrect calculation", "Syntactic error", "Functional error", "Error handling error", "Communication error" }));

        jTextField8.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setBorder(null);
        jTextField8.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField8.setMargin(new java.awt.Insets(2, 20, 2, 2));

        jTextField9.setBackground(new java.awt.Color(224, 224, 224));
        jTextField9.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(null);
        jTextField9.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField9.setMargin(new java.awt.Insets(2, 20, 2, 2));

        jTextField10.setBackground(new java.awt.Color(224, 224, 224));
        jTextField10.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("YYYY-MM-DD");
        jTextField10.setBorder(null);
        jTextField10.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField10.setMargin(new java.awt.Insets(2, 20, 2, 2));

        jButton3.setFont(new java.awt.Font("Serif", 2, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Add Bug");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("2 - AssignBug    ---------------------------------------------------------------------------");

        jTextField11.setBackground(new java.awt.Color(224, 224, 224));
        jTextField11.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setBorder(null);
        jTextField11.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField11.setMargin(new java.awt.Insets(2, 20, 2, 2));

        jTextField12.setBackground(new java.awt.Color(224, 224, 224));
        jTextField12.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setBorder(null);
        jTextField12.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField12.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setBackground(new java.awt.Color(224, 224, 224));
        jTextField13.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(null);
        jTextField13.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField13.setMargin(new java.awt.Insets(2, 20, 2, 2));

        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 2, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Assign");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("4- Attach Screenshot -------------------------------------------------------------------");

        jButton10.setFont(new java.awt.Font("Segoe UI Semibold", 2, 20)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 255));
        jButton10.setText("Show Bugs");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jButton15.setText("Browse Screenshot");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jTextField16.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setBorder(null);
        jTextField16.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField16.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField16.setOpaque(false);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("3 - Monitor    ---------------------------------------------------------------------------");

        jLabel19.setBackground(new java.awt.Color(255, 51, 51));
        jLabel19.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 255, 255));

        jButton16.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 51, 255));
        jButton16.setText("Attach ScreenShot");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 255));
        jLabel20.setText("Bug Name");

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 255));
        jLabel21.setText("Project name");

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 255));
        jLabel22.setText("Bug Level");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 255));
        jLabel23.setText("Bug Status");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 51, 255));
        jLabel24.setText("Date");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 255, 51));
        jLabel25.setText("Dev Name");

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 255, 51));
        jLabel26.setText("Bug Name");

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 255, 51));
        jLabel27.setText("Bug Name");

        org.jdesktop.layout.GroupLayout testerinterfaceLayout = new org.jdesktop.layout.GroupLayout(testerinterface);
        testerinterface.setLayout(testerinterfaceLayout);
        testerinterfaceLayout.setHorizontalGroup(
            testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testerinterfaceLayout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel2)
                .add(0, 0, Short.MAX_VALUE)
                .add(jLabel1)
                .add(387, 387, 387))
            .add(testerinterfaceLayout.createSequentialGroup()
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(testerinterfaceLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(testerinterfaceLayout.createSequentialGroup()
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel21)
                                        .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(174, 174, 174)
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(testerinterfaceLayout.createSequentialGroup()
                                            .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(testerinterfaceLayout.createSequentialGroup()
                                                    .add(251, 251, 251)
                                                    .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(137, 137, 137))
                                                .add(testerinterfaceLayout.createSequentialGroup()
                                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(18, 18, 18)))
                                            .add(jComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(testerinterfaceLayout.createSequentialGroup()
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(jTextField9)
                                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(48, 48, 48)
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(testerinterfaceLayout.createSequentialGroup()
                                            .add(10, 10, 10)
                                            .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 394, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(testerinterfaceLayout.createSequentialGroup()
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(51, 51, 51)
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(64, 64, 64)
                                    .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 999, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 999, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 999, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, testerinterfaceLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, testerinterfaceLayout.createSequentialGroup()
                                .add(jButton10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 349, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(271, 271, 271))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, testerinterfaceLayout.createSequentialGroup()
                                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(209, 209, 209)
                                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(101, 101, 101))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, testerinterfaceLayout.createSequentialGroup()
                                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 442, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(227, 227, 227))))
                    .add(testerinterfaceLayout.createSequentialGroup()
                        .add(136, 136, 136)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(testerinterfaceLayout.createSequentialGroup()
                                .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(testerinterfaceLayout.createSequentialGroup()
                                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jButton15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .add(jTextField16)
                                    .add(jSeparator8))
                                .add(38, 38, 38)
                                .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 243, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))
                        .add(109, 109, 109)
                        .add(jButton16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(27, 27, 27)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        testerinterfaceLayout.setVerticalGroup(
            testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testerinterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(1, 1, 1)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(testerinterfaceLayout.createSequentialGroup()
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(testerinterfaceLayout.createSequentialGroup()
                        .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(testerinterfaceLayout.createSequentialGroup()
                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
                        .add(jButton3)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel25)
                    .add(jLabel26))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .add(3, 3, 3)
                .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel27)
                .add(1, 1, 1)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton16))
                .add(1, 1, 1)
                .add(jSeparator8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(testerinterfaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton15)
                    .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 20, Short.MAX_VALUE))
        );

        jLayeredPane1.add(testerinterface, "card2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Cambria", 2, 16)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(230, 230, 230));
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("Username");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField1.setOpaque(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(230, 230, 230));
        jTextField2.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("Password");
        jTextField2.setBorder(null);
        jTextField2.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jTextField2.setOpaque(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jButton5.setText("Show All users");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton18.setText("jButton18");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jSeparator14.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator15.setBackground(new java.awt.Color(102, 102, 102));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(73, 73, 73)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .add(jTextField2)
                    .add(jSeparator14)
                    .add(jSeparator15))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jButton5)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(153, 153, 153)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButton18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(57, 57, 57)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22)
                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jButton5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(jButton2)
                .add(60, 60, 60)
                .add(jButton18))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1080, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLayeredPane1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(157, 157, 157)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GlobalFunctions g = new GlobalFunctions();
        JFrame nullpop = new JFrame();
        String s = jTextField1.getText();
        int pw = Integer.parseInt(jTextField2.getText());
        int x;
        JFrame f = new JFrame();
        String check = g.checkuser(s,pw);
        if (check == null)
        {
            JOptionPane.showMessageDialog(nullpop,"User not Found");
        }
        else if (check.equals("admin"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(admininterface);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        else if ( check.equals("tester"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(testerinterface);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
            x = g.checkemail(s);
            if ( x == 0)
            {
                JOptionPane.showMessageDialog(f,"No New Emails");
            }
            else if (x == 1)
            {
                JOptionPane.showMessageDialog(f,"You Have New Emails\nCheck All Bugs");
                JTable t = new JTable(); 
            }
        }
        else if (check.equals("pm"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(pminterface);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        else if (check.equals("developer"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(devinterface);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
            x = g.checkemail(s);
            if ( x == 0)
            {
                JOptionPane.showMessageDialog(f,"No New Emails");
            }
            else if (x == 1)
            {
                JOptionPane.showMessageDialog(f,"You Have New Emails\nCheck Assigned Bugs");
                JTable t = new JTable(); 
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Admin admin = new Admin();
        JTable t = new JTable(); 
        ResultSet rs = admin.displayall();   
        t.setModel(DbUtils.resultSetToTableModel(rs));
        JScrollPane sp =new JScrollPane(t);
        JFrame f = new JFrame();
        f.setSize(1000,1000);
        f.add(sp);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Admin admin = new Admin();
        String name = jTextField5.getText();
        if (admin.checkuserByNameOnly(name) == 1)
        {
            admin.deleteuser(name);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"Deleted Successfully!");
        }
        else
        {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"User Not Found!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Admin admin = new Admin();
        String newname = jTextField4.getText();
        String newrole = (String)jComboBox2.getSelectedItem();
        if (admin.checkuserByNameOnly(newname) == 1)
        {
            admin.updateuser(newname,newrole);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"Updated Successfully!");
        }
        else
        {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"User Not Found!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Admin admin = new Admin();
        String name = jTextField6.getText();
        String role = (String)jComboBox1.getSelectedItem();
        int pw = Integer.parseInt(jTextField7.getText());
        admin.adduser(name,pw,role);
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f,"Added Successfully!");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        jTextField6.setText("");
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        jTextField7.setText("");
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tester tester = new Tester();
        String name = jTextField3.getText();
        String type = (String)jComboBox4.getSelectedItem();
        String pri = (String)jComboBox3.getSelectedItem();
        int lvl = Integer.parseInt(jTextField8.getText());
        String proj_name = jTextField9.getText();
        String date = jTextField10.getText();
        String status = jTextField11.getText();
        String testerdef = jTextField1.getText();
        tester.define(name,type,pri,lvl,proj_name,date,status,testerdef);
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f,"Added Successfully!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Tester tester = new Tester();
        String bugname = jTextField12.getText();
        String devname = jTextField13.getText();
        JFrame f = new JFrame();
        if (tester.checkuserByNameOnly(devname) == 1 && tester.checkBugByNameOnly(bugname) == 1)
        {
            tester.assign(bugname,devname);
            JOptionPane.showMessageDialog(f,"Bug has been Assigned Succesfully!!");
        }
        else
        {
            JOptionPane.showMessageDialog(f,"Error Check Username And BugName Again");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        GlobalFunctions g = new GlobalFunctions();
        JTable t = new JTable(); 
        ResultSet rs = g.displayallusers();   
        t.setModel(DbUtils.resultSetToTableModel(rs));
        JScrollPane sp =new JScrollPane(t);
        JFrame f = new JFrame();
        f.setSize(1000,500);
        f.add(sp);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Tester tester = new Tester();
        JTable t = new JTable(); 
        ResultSet rs = tester.displayall();   
        t.setModel(DbUtils.resultSetToTableModel(rs));
        JScrollPane sp =new JScrollPane(t);
        JFrame f = new JFrame();
        f.setSize(1000,500);
        f.add(sp);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //////////////////////////////////////////////////// ----------------> CHANGE STATUES ////////////////////////
        Developer dev = new Developer();
        String bugname = jTextField14.getText();
        String status = (String)jComboBox5.getSelectedItem();
        JFrame f = new JFrame();
        if (dev.checkBugByNameOnly(bugname) == 1)
        {
            dev.changestatus(status,bugname);
            JOptionPane.showMessageDialog(f,"Bug Status has been Changed Succesfully!!");
        }
        else
        {
            JOptionPane.showMessageDialog(f,"Bug Not found.");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Developer dev = new Developer();
        JTable t = new JTable(); 
        ResultSet rs = dev.displayassigned(jTextField1.getText());   
        t.setModel(DbUtils.resultSetToTableModel(rs));
        JScrollPane sp =new JScrollPane(t);
        JFrame f = new JFrame();
        f.setSize(1000,500);
        f.add(sp);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        GlobalFunctions g = new GlobalFunctions();
        JTable t = new JTable(); 
        ResultSet rs = g.displayall();   
        t.setModel(DbUtils.resultSetToTableModel(rs));
        JScrollPane sp =new JScrollPane(t);
        JFrame f = new JFrame();
        f.setSize(1000,500);
        f.add(sp);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        PM pm = new PM();
        String devname = jTextField15.getText();
        if (pm.checkuserbynameandrole(devname,"Developer") != 0)
        {
            int allbugs = pm.assignedbugnum(devname);
            int solvedbugs = pm.checksolvednum(devname);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,devname + " Has " + allbugs + " Assigned Bugs\n And " + solvedbugs + " of them are solved");
        }
        else
        {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"User Not Found");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        JFileChooser filechooser = new JFileChooser(); 
        String src = "";
        int action_pressed = filechooser.showOpenDialog(null);
        if (action_pressed == filechooser.APPROVE_OPTION)
        {
            src = filechooser.getSelectedFile().getAbsolutePath();
            /*JFrame imageframe = new JFrame();
            imageframe.setSize(1366,782);
            imageframe.setLocationRelativeTo(null);
            ImageIcon img = new ImageIcon(filechooser.getSelectedFile().getAbsolutePath());
            JLabel lbl = new JLabel();
            lbl.setText("");
            lbl.setIcon(img);
            imageframe.add(lbl);
            imageframe.setVisible(true);*/
        }
        jLabel19.setText(src);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Tester tester = new Tester();
        String bugname = jTextField16.getText();
        String src = jLabel19.getText();
        JFrame f = new JFrame();
        if (tester.checkBugByNameOnly(bugname) == 1)
        {
            tester.assignscreen(bugname,src);
            JOptionPane.showMessageDialog(f,"Screenshot Attached Succesfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(f,"Bug Not found.");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        PM pm = new PM();
        String testername = jTextField17.getText();
        if (pm.checkuserbynameandrole(testername,"Tester") != 0)
        {
            int defcount = pm.definednum(testername);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,testername + " Has Defined " + defcount + " Bugs");
        }
        else
        {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"User Not Found");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
            GlobalFunctions g = new GlobalFunctions();
            String bugname = jTextField16.getText();
            String s = g.returnsrc(bugname);
            JFrame imageframe = new JFrame();
            imageframe.setSize(1366,782);
            imageframe.setLocationRelativeTo(null);
            ImageIcon img = new ImageIcon(s);
            JLabel lbl = new JLabel();
            lbl.setText("");
            lbl.setIcon(img);
            imageframe.add(lbl);
            imageframe.setVisible(true);
            // تم بحمد الله الانتهاء من البروجيكت
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admininterface;
    private javax.swing.JPanel devinterface;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pminterface;
    private javax.swing.JPanel testerinterface;
    // End of variables declaration//GEN-END:variables

}
